// import pizza1 from '../src/assets/images/dodobbq.webp';
// import pizza2 from '../src/assets/images/cheesePizza.webp';

// export const pizzaData = [
//   {
//     id: 1,
//     name: 'Veggie Overload',
//     description: 'Pizza 1 description and some description',
//     base: 'Greek Pizza',
//     sauce: 'Pesto Sauce',
//     cheese: 'Provolone cheese',
//     veggies: [
//       'Fresh tomatoes',
//       'Onions',
//       'Arugula',
//       'Kale',
//       'Egg plants',
//       'Bell peppers',
//       'Spinach',
//       'Zucchini',
//       'Mushrooms',
//       'Olives',
//       'Red onion',
//       'Corn',
//     ],
//     price: 100,
//     image: pizza1,
//   },
//   {
//     id: 2,
//     name: 'Half and Half Pizza',
//     description: 'Pizza 1 description and some description',
//     base: 'Greek Pizza',
//     sauce: 'Pesto Sauce',
//     cheese: 'Provolone cheese',
//     veggies: [
//       'Fresh tomatoes',
//       'Onions',
//       'Arugula',
//       'Kale',
//       'Egg plants',
//       'Bell peppers',
//       'Spinach',
//       'Zucchini',
//       'Mushrooms',
//       'Olives',
//       'Red onion',
//       'Corn',
//     ],
//     price: 200,
//     image: pizza2,
//   },
//   {
//     id: 3,
//     name: 'Plantain BBQ',
//     description: 'Pizza 1 description and some description',
//     base: 'Greek Pizza',
//     sauce: 'Pesto Sauce',
//     cheese: 'Provolone cheese',
//     veggies: [
//       'Fresh tomatoes',
//       'Onions',
//       'Arugula',
//       'Kale',
//       'Egg plants',
//       'Bell peppers',
//       'Spinach',
//       'Zucchini',
//       'Mushrooms',
//       'Olives',
//       'Red onion',
//       'Corn',
//     ],
//     price: 300,
//     image: pizza1,
//   },
//   {
//     id: 4,
//     name: 'Mexican Beef Pizza',
//     description: 'Pizza 1 description and some description',
//     base: 'Greek Pizza',
//     sauce: 'Pesto Sauce',
//     cheese: 'Provolone cheese',
//     veggies: [
//       'Fresh tomatoes',
//       'Onions',
//       'Arugula',
//       'Kale',
//       'Egg plants',
//       'Bell peppers',
//       'Spinach',
//       'Zucchini',
//       'Mushrooms',
//       'Olives',
//       'Red onion',
//       'Corn',
//     ],
//     price: 400,
//     image: pizza2,
//   },
//   {
//     id: 5,
//     name: 'CheeseBurger Pizza',
//     description: 'Pizza 1 description and some description',
//     base: 'Greek Pizza',
//     sauce: 'Pesto Sauce',
//     cheese: 'Provolone cheese',
//     veggies: [
//       'Fresh tomatoes',
//       'Onions',
//       'Arugula',
//       'Kale',
//       'Egg plants',
//       'Bell peppers',
//       'Spinach',
//       'Zucchini',
//       'Mushrooms',
//       'Olives',
//       'Red onion',
//       'Corn',
//     ],
//     price: 500,
//     image: pizza1,
//   },
//   {
//     id: 6,
//     name: 'Chicken BBQ',
//     description: 'Pizza 1 description and some description',
//     base: 'Greek Pizza',
//     sauce: 'Pesto Sauce',
//     cheese: 'Provolone cheese',
//     veggies: [
//       'Fresh tomatoes',
//       'Onions',
//       'Arugula',
//       'Kale',
//       'Egg plants',
//       'Bell peppers',
//       'Spinach',
//       'Zucchini',
//       'Mushrooms',
//       'Olives',
//       'Red onion',
//       'Corn',
//     ],
//     price: 600,
//     image: pizza2,
//   },
//   {
//     id: 7,
//     name: 'Chicken BBQ',
//     description: 'Pizza 1 description and some description',
//     base: 'Greek Pizza',
//     sauce: 'Pesto Sauce',
//     cheese: 'Provolone cheese',
//     veggies: [
//       'Fresh tomatoes',
//       'Onions',
//       'Arugula',
//       'Kale',
//       'Egg plants',
//       'Bell peppers',
//       'Spinach',
//       'Zucchini',
//       'Mushrooms',
//       'Olives',
//       'Red onion',
//       'Corn',
//     ],
//     price: 600,
//     image: pizza2,
//   },
//   {
//     id: 8,
//     name: 'Chicken BBQ',
//     description: 'Pizza 1 description and some description',
//     base: 'Greek Pizza',
//     sauce: 'Pesto Sauce',
//     cheese: 'Provolone cheese',
//     veggies: [
//       'Fresh tomatoes',
//       'Onions',
//       'Arugula',
//       'Kale',
//       'Egg plants',
//       'Bell peppers',
//       'Spinach',
//       'Zucchini',
//       'Mushrooms',
//       'Olives',
//       'Red onion',
//       'Corn',
//     ],
//     price: 600,
//     image: pizza2,
//   },
//   {
//     id: 9,
//     name: 'Chicken BBQ',
//     description: 'Pizza 1 description and some description',
//     base: 'Greek Pizza',
//     sauce: 'Pesto Sauce',
//     cheese: 'Provolone cheese',
//     veggies: [
//       'Fresh tomatoes',
//       'Onions',
//       'Arugula',
//       'Kale',
//       'Egg plants',
//       'Bell peppers',
//       'Spinach',
//       'Zucchini',
//       'Mushrooms',
//       'Olives',
//       'Red onion',
//       'Corn',
//     ],
//     price: 600,
//     image: pizza2,
//   },
//   {
//     id: 10,
//     name: 'Chicken BBQ',
//     description: 'Pizza 1 description and some description',
//     base: 'Greek Pizza',
//     sauce: 'Pesto Sauce',
//     cheese: 'Provolone cheese',
//     veggies: [
//       'Fresh tomatoes',
//       'Onions',
//       'Arugula',
//       'Kale',
//       'Egg plants',
//       'Bell peppers',
//       'Spinach',
//       'Zucchini',
//       'Mushrooms',
//       'Olives',
//       'Red onion',
//       'Corn',
//     ],
//     price: 600,
//     image: pizza2,
//   },
// ];
